# Generated by Django 5.2.4 on 2025-08-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"ordering": ["label"]},
        ),
        migrations.AlterModelOptions(
            name="isamemberof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="isrelatedto",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="livesin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["surname"]},
        ),
        migrations.AlterModelOptions(
            name="place",
            options={"ordering": ["label"]},
        ),
        migrations.AlterModelOptions(
            name="profession",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="worksfor",
            options={"ordering": ["pk"]},
        ),
    ]
