# Generated by Django 5.2.4 on 2026-02-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0002_alter_group_options_alter_isamemberof_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="feature_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text='<a href="https://www.geonames.org/export/codes.html" target="_blank">Geonames Feature Code List</a>',
                max_length=16,
                verbose_name="feature code",
            ),
        ),
        migrations.AlterField(
            model_name="versionplace",
            name="feature_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text='<a href="https://www.geonames.org/export/codes.html" target="_blank">Geonames Feature Code List</a>',
                max_length=16,
                verbose_name="feature code",
            ),
        ),
    ]
