# Generated by Django 5.2.4 on 2026-03-18 11:47

import apis_ontology.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0003_alter_place_feature_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="alternative_names",
            field=apis_ontology.fields.AlternativeLabelsField(
                blank=True, null=True, verbose_name="Alternative names"
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="alternative_labels",
            field=apis_ontology.fields.AlternativeLabelsField(
                blank=True, null=True, verbose_name="Alternative labels"
            ),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="alternative_names",
            field=apis_ontology.fields.AlternativeLabelsField(
                blank=True, null=True, verbose_name="Alternative names"
            ),
        ),
        migrations.AddField(
            model_name="versionplace",
            name="alternative_labels",
            field=apis_ontology.fields.AlternativeLabelsField(
                blank=True, null=True, verbose_name="Alternative labels"
            ),
        ),
    ]
